name: xcube-smos
channels:
  - conda-forge
  - defaults
dependencies:
  - click
  - fsspec
  - h5netcdf
  - h5py
  - importlib_resources
  - numpy
  - numba
  - pandas
  - xarray
  - xcube
  # Optional
  #- kerchunk
  # Development
  - pytest
