site_name: xcube-smos

copyright: Copyright &copy; 2024 Brockmann Consult

nav:
  - Overview: index.md

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: light green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dcs4copy/xcube-smos
    - icon: fontawesome/brands/python
      link: https://github.com/dcs4cop/xcube-smos/releases

plugins:
  - search
  - autorefs
