name: Unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-xcube-smos
        uses: actions/checkout@v4
      # Set up micromamba build environment
      - name: setup-micromamba-xcube-smos
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.5.6-0'
          environment-file: environment.yml
          # Install kerchunk explicitly, since it's not included in the
          # environment file.
          create-args: kerchunk
          init-shell: >-
            bash
          cache-environment: true
          post-cleanup: 'all'
      # Set up xcube
      - name: setup-xcube-smos
        shell: bash -l {0}
        run: |
          micromamba info
          micromamba list
          python setup.py develop
      # Run unit tests
      - name: unittest-xcube-smos
        shell: bash -l {0}
        run: |
          pip install pytest pytest-cov
          pytest --cov=./ --cov-report=xml
      # Run coverage check
      - name: coverage-xcube-smos
        uses: codecov/codecov-action@v3
        with:
          verbose: true # optional (default = false)
